//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace task4.Models.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class StuTable
    {
        public string Name { get; set; }
        public string id { get; set; }
        public string Department { get; set; }
        public string Dob { get; set; }
        public Nullable<double> cgpa { get; set; }
    }
}
